import React,{useEffect,useState}from"react";import{useParams,useNavigate,Link}from"react-router-dom";import{MapPin,Calendar,ShieldCheck,MessageCircle,Send,X,ClipboardCheck,Clock,CheckCircle2,XCircle,Flag,PackageCheck}from"lucide-react";import Loader from"../components/Loader";import MatchList from"../components/MatchList";import ClaimForm from"../components/ClaimForm";import ClaimsInbox from"../components/ClaimsInbox";import{getItemById,getPotentialMatches,startChatAboutItem,getMyClaimForItem,markItemReturned,reportItemAbuse}from"../services/api";import{useAuth}from"../context/AuthContext";
function defaultMessageFor(item){return item.itemKind==="found"?`Hi ${item.reporterName}, I think the ${item.name.toLowerCase()} you found might be mine. Can we talk about getting it back?`:`Hi ${item.reporterName}, I think I found your ${item.name.toLowerCase()}. Let's connect so I can return it to you.`}
const CLAIM={pending:{icon:Clock,text:"Claim submitted — pending review",className:"bg-amber-50 text-amber-700"},approved:{icon:CheckCircle2,text:"Claim accepted!",className:"bg-brand-50 text-brand-700"},rejected:{icon:XCircle,text:"Claim was rejected",className:"bg-red-50 text-red-600"}};
export default function ItemDetail(){const{id}=useParams();const navigate=useNavigate();const{isAuthenticated,user}=useAuth();const[item,setItem]=useState(null);const[matches,setMatches]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[composerOpen,setComposerOpen]=useState(false);const[messageText,setMessageText]=useState("");const[sending,setSending]=useState(false);const[sendError,setSendError]=useState("");const[claimOpen,setClaimOpen]=useState(false);const[myClaim,setMyClaim]=useState(null);const[returning,setReturning]=useState(false);const[reporting,setReporting]=useState(false);const[reportReason,setReportReason]=useState("");const[reportDetails,setReportDetails]=useState("");const isOwner=Boolean(isAuthenticated&&user?.id&&item?.reportedBy&&String(user.id)===String(item.reportedBy));
 const load=()=>{setLoading(true);Promise.all([getItemById(id),getPotentialMatches(id)]).then(([i,m])=>{setItem(i);setMatches(m)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[id]);useEffect(()=>{if(!item||item.itemKind!=="found"||isOwner||!isAuthenticated)return;getMyClaimForItem(item.id).then(setMyClaim).catch(()=>setMyClaim(null))},[item,isOwner,isAuthenticated]);
 const contact=()=>{if(!isAuthenticated){navigate("/login");return}if(!messageText)setMessageText(defaultMessageFor(item));setComposerOpen(true)};const send=async e=>{e.preventDefault();setSending(true);setSendError("");try{const result=await startChatAboutItem(item,messageText);navigate(`/messages/${result.id}`)}catch(e){setSendError(e.message)}finally{setSending(false)}};
 const markReturned=async()=>{setReturning(true);try{const updated=await markItemReturned(item.id);setItem(updated)}catch(e){setError(e.message)}finally{setReturning(false)}};
 const report=async e=>{e.preventDefault();if(!reportReason.trim())return;setReporting(true);try{await reportItemAbuse(item.id,{reason:reportReason,details:reportDetails});setReportReason("");setReportDetails("");alert("Report submitted to moderation.")}catch(e){setError(e.message)}finally{setReporting(false)}};
 if(loading)return <Loader label="Loading item..."/>;if(error&&!item)return <p className="p-8 text-center text-sm text-red-500">{error}</p>;if(!item)return null;const claimStyle=myClaim?CLAIM[myClaim.status]:null;
 return <div className="mx-auto max-w-2xl px-4 py-8 sm:px-8"><div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-card"><span className={`mb-3 inline-block rounded-full px-3 py-1 text-xs font-semibold ${item.itemKind==="found"?"bg-brand-100 text-brand-700":"bg-amber-100 text-amber-700"}`}>{item.itemKind==="found"?"Found item":"Lost item"}</span><h1 className="text-2xl font-semibold">{item.name}</h1><p className="mt-2 text-gray-600">{item.description}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm text-gray-500"><span className="flex items-center gap-1.5"><MapPin size={14}/>{item.location}</span><span className="flex items-center gap-1.5"><Calendar size={14}/>{new Date(item.date).toLocaleDateString()}</span>{item.contactVerified&&<span className="flex items-center gap-1.5 text-brand-700"><ShieldCheck size={14}/>Phone verified</span>}</div><div className="mt-5 flex items-center justify-between gap-3 rounded-lg bg-gray-50 px-4 py-3"><p className="text-sm text-gray-600">Reported by <Link className="font-medium text-gray-900 hover:underline" to={`/u/${item.reportedBy}`}>{item.reporterName}</Link></p>{item.itemKind==="found"?!isOwner&&!myClaim&&!claimOpen?<button onClick={()=>{if(!isAuthenticated)return navigate("/login");setClaimOpen(true)}} className="flex shrink-0 items-center gap-1.5 rounded-lg bg-brand-700 px-4 py-2 text-sm text-white"><ClipboardCheck size={16}/> Claim this item</button>:!isOwner&&item.status==="open"&&!composerOpen?<button onClick={contact} className="flex items-center gap-1.5 rounded-lg bg-brand-700 px-4 py-2 text-sm text-white"><MessageCircle size={16}/> Message reporter</button>:null:!composerOpen&&!isOwner?<button onClick={contact} className="flex items-center gap-1.5 rounded-lg bg-brand-700 px-4 py-2 text-sm text-white"><MessageCircle size={16}/> I found this</button>:null}</div>
 {claimStyle&&<div className={`mt-3 flex items-center gap-2 rounded-lg px-4 py-3 text-sm font-medium ${claimStyle.className}`}>{React.createElement(claimStyle.icon,{size:16})}{claimStyle.text}</div>}
 {claimOpen&&!myClaim&&<ClaimForm item={item} onCancel={()=>setClaimOpen(false)} onSubmitted={c=>{setMyClaim(c);setClaimOpen(false)}}/>}
 {isOwner&&item.itemKind==="found"&&<div className="mt-5"><p className="mb-2 text-sm font-semibold">Claims on this item</p><ClaimsInbox itemId={item.id}/>{item.status!=="returned"&&<button onClick={markReturned} disabled={returning} className="mt-3 flex items-center gap-1.5 rounded-lg bg-brand-700 px-4 py-2 text-sm text-white disabled:opacity-60"><PackageCheck size={16}/>{returning?"Marking returned...":"Mark item returned"}</button>}</div>}
 {composerOpen&&<form onSubmit={send} className="mt-3 rounded-lg border bg-gray-50 p-4"><div className="mb-2 flex justify-between"><p className="text-xs font-medium text-gray-500">Message to {item.reporterName}</p><button type="button" onClick={()=>setComposerOpen(false)}><X size={16}/></button></div><textarea value={messageText} onChange={e=>setMessageText(e.target.value)} rows={3} className="w-full rounded-lg border bg-white px-3 py-2.5 text-sm"/>{sendError&&<p className="mt-1 text-xs text-red-500">{sendError}</p>}<button disabled={sending||!messageText.trim()} className="mt-3 flex items-center gap-1.5 rounded-lg bg-brand-700 px-4 py-2 text-sm text-white disabled:opacity-60"><Send size={14}/>{sending?"Sending...":"Send message"}</button></form>}
 {!isOwner&&isAuthenticated&&<form onSubmit={report} className="mt-5 rounded-lg border border-red-100 bg-red-50/40 p-4"><p className="flex items-center gap-1.5 text-sm font-medium text-red-700"><Flag size={14}/> Report this item</p><div className="mt-2 flex gap-2"><input value={reportReason} onChange={e=>setReportReason(e.target.value)} placeholder="Reason" maxLength={200} className="flex-1 rounded-lg border px-3 py-2 text-sm"/><button disabled={reporting||!reportReason.trim()} className="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-600">Report</button></div><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value.slice(0,2000))} rows={2} placeholder="Additional details (optional)" className="mt-2 w-full rounded-lg border px-3 py-2 text-sm"/></form>}
 {item.status==="returned"&&<div className="mt-4 rounded-lg bg-brand-50 p-3 text-sm text-brand-700">This item has been marked as returned.</div>}</div><div className="mt-8"><h2 className="mb-1 text-lg font-semibold">Possible {item.itemKind==="found"?"lost":"found"} matches</h2><p className="mb-4 text-sm text-gray-500">Ranked by how closely the descriptions line up — no photos needed.</p><MatchList matches={matches}/></div>{!isAuthenticated&&<p className="mt-6 text-center text-sm text-gray-500"><Link to="/login" className="font-medium text-brand-700">Sign in</Link> to contact users.</p>}</div>;
}
