import React, { useEffect, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Mail, ShieldCheck, ShieldAlert, Bell, UserX, LifeBuoy, LogOut, ChevronRight, Pencil, Shield } from "lucide-react";
import Loader from "../components/Loader";
import OtpField from "../components/OtpField";
import ToggleSwitch from "../components/ToggleSwitch";
import { getProfile, updateProfile, updateNotificationPrefs, getBlockedUsers, contactSupport } from "../services/api";
import { useAuth } from "../context/AuthContext";

export default function Settings(){const navigate=useNavigate();const {logout,updateUser,isAdmin}=useAuth();const [profile,setProfile]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [blockedCount,setBlockedCount]=useState(0);const [verifying,setVerifying]=useState(false);const [phone,setPhone]=useState("");
 const load=()=>{setLoading(true);getProfile().then(p=>{setProfile(p);setPhone(p.phone||"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false));getBlockedUsers().then(x=>setBlockedCount(x.length)).catch(()=>{});};useEffect(load,[]);
 const handleVerified=async()=>{const updated=await updateProfile({phone});setProfile(updated);updateUser(updated);setVerifying(false);};
 const toggle=async(key,value)=>{setProfile(p=>({...p,notificationPrefs:{...p.notificationPrefs,[key]:value}}));try{await updateNotificationPrefs({[key]:value});}catch(e){setError(e.message);}};
 const support=async()=>{try{const chat=await contactSupport();navigate(`/messages/${chat._id}`);}catch(e){setError(e.message);}};
 if(loading)return <Loader label="Loading settings..."/>;if(error&&!profile)return <div className="p-8 text-center text-sm text-red-500">{error}</div>;if(!profile)return null;
 return <div className="mx-auto max-w-2xl px-4 py-8 sm:px-8"><h1 className="text-2xl font-semibold">Settings</h1><p className="mt-1 text-sm text-gray-500">Manage your account, notifications, privacy and security.</p>{error&&<p className="mt-3 text-sm text-red-500">{error}</p>}
 <section className="mt-6 rounded-2xl border bg-white p-6 shadow-card"><p className="mb-3 text-sm font-semibold">Account</p><div className="flex items-center justify-between gap-3 py-2"><div className="flex items-center gap-2 text-sm"><Mail size={16} className="text-gray-400"/>{profile.email}</div><Link to="/profile/edit" className="flex items-center gap-1 text-xs font-medium text-brand-700"><Pencil size={12}/> Edit</Link></div><div className="flex items-center justify-between gap-3 py-2"><div className="flex items-center gap-2 text-sm">{profile.phoneVerified?<ShieldCheck className="text-brand-600" size={16}/>:<ShieldAlert className="text-amber-500" size={16}/>} {profile.phone||"No phone on file"}</div>{profile.phoneVerified?<span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs text-brand-700">Verified</span>:!verifying&&<button onClick={()=>setVerifying(true)} className="rounded-full bg-amber-50 px-2.5 py-1 text-xs text-amber-700">Verify now</button>}</div>{verifying&&!profile.phoneVerified&&<div className="mt-2 rounded-lg bg-gray-50 p-4"><OtpField phone={phone} onPhoneChange={setPhone} verified={false} onVerified={handleVerified}/></div>}</section>
 <section className="mt-4 rounded-2xl border bg-white p-6 shadow-card"><p className="mb-3 flex items-center gap-2 text-sm font-semibold"><Bell size={16}/> Notifications</p><div className="divide-y">{[["newMatches","New matches","When a lost/found report closely matches yours"],["messages","Messages","New chat messages from other users"],["itemUpdates","Item updates","Status changes on items you've reported"],["promotions","Promotions","Occasional news and tips from LosttoFound"]].map(([key,label,description])=><ToggleSwitch key={key} label={label} description={description} checked={profile.notificationPrefs?.[key] ?? false} onChange={(v)=>toggle(key,v)}/>)}</div></section>
 <section className="mt-4 overflow-hidden rounded-2xl border bg-white shadow-card"><Link to="/settings/blocked" className="flex items-center justify-between px-6 py-4 text-sm"><span className="flex items-center gap-2"><UserX size={16}/> Blocked users</span><span className="flex items-center gap-2 text-gray-400">{blockedCount>0&&blockedCount}<ChevronRight size={16}/></span></Link><button onClick={support} className="flex w-full items-center justify-between border-t px-6 py-4 text-sm"><span className="flex items-center gap-2"><LifeBuoy size={16}/> Contact support</span><ChevronRight size={16}/></button>{isAdmin&&<Link to="/admin" className="flex items-center gap-2 border-t px-6 py-4 text-sm font-medium text-brand-700"><Shield size={16}/> Admin moderation</Link>}<button onClick={()=>{logout();navigate("/login")}} className="flex w-full items-center gap-2 border-t px-6 py-4 text-sm font-medium text-red-600"><LogOut size={16}/> Log out</button></section></div>;
}
